sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

os:
  - linux
  - osx

rvm:
  - ruby-head
  - 1.9.3
  - 2.3.1

language: ruby

before_install:
  - gem install bundler

script: bin/bundle exec rspec
