sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

os:
  - linux
  - osx

rvm:
  - 2.3.3

language: ruby

cache: bundler

before_install:
  - gem install bundler

script: bin/bundle exec rspec
