sudo: false

os:
  - linux

rvm:
  - 2.3.3

language: ruby

cache: bundler

before_install:
  - gem install bundler
  - cp config/database.sample.yml config/database.yml

script:
  - bin/bundle exec rspec
