# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d322f0d42628f98c33efce59860ed5f6dad593d9593a93a0398e00fa8da8e7b6ac19aca3febcec94a41da64d33582925cf0726fed0e9fe2127dc77a97c1b589e
  saml_idp_cert: |
    -----BEGIN CERTIFICATE-----
    MIICizCCAfQCCQCY8tKaMc0BMjANBgkqhkiG9w0BAQUFADCBiTELMAkGA1UEBhMC
    Tk8xEjAQBgNVBAgTCVRyb25kaGVpbTEQMA4GA1UEChMHVU5JTkVUVDEOMAwGA1UE
    CxMFRmVpZGUxGTAXBgNVBAMTEG9wZW5pZHAuZmVpZGUubm8xKTAnBgkqhkiG9w0B
    CQEWGmFuZHJlYXMuc29sYmVyZ0B1bmluZXR0Lm5vMB4XDTA4MDUwODA5MjI0OFoX
    DTM1MDkyMzA5MjI0OFowgYkxCzAJBgNVBAYTAk5PMRIwEAYDVQQIEwlUcm9uZGhl
    aW0xEDAOBgNVBAoTB1VOSU5FVFQxDjAMBgNVBAsTBUZlaWRlMRkwFwYDVQQDExBv
    cGVuaWRwLmZlaWRlLm5vMSkwJwYJKoZIhvcNAQkBFhphbmRyZWFzLnNvbGJlcmdA
    dW5pbmV0dC5ubzCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAt8jLoqI1VTlx
    AZ2axiDIThWcAOXdu8KkVUWaN/SooO9O0QQ7KRUjSGKN9JK65AFRDXQkWPAu4Hln
    O4noYlFSLnYyDxI66LCr71x4lgFJjqLeAvB/GqBqFfIZ3YK/NrhnUqFwZu63nLrZ
    jcUZxNaPjOOSRSDaXpv1kb5k3jOiSGECAwEAATANBgkqhkiG9w0BAQUFAAOBgQBQ
    Yj4cAafWaYfjBU2zi1ElwStIaJ5nyp/s/8B8SAPK2T79McMyccP3wSW13LHkmM1j
    wKe3ACFXBvqGQN0IbcH49hu0FKhYFM/GPDJcIHFBsiyMBXChpye9vBaTNEBCtU3K
    jjyG0hRT2mAQ9h+bkPmOvlEo/aH0xR68Z9hw4PF13w==
    -----END CERTIFICATE-----
  saml_idp_sso_target_url: 'https://openidp.feide.no/simplesaml/saml2/idp/SSOService.php'
  saml_issuer: 'mybookingsapp'
  saml_name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
  saml_provider_name: 'saml'

test:
  secret_key_base: 250c2f28f99ca1df014b103e7ce999c4c47aefe26a60ca5881bf41ae5c91ecc7e6ff8714c448cab42b4ae13a77fb31bd1395e5c80118fa3c5c40f0c06ae89059
  saml_idp_cert: |
    -----BEGIN CERTIFICATE-----
    MIICizCCAfQCCQCY8tKaMc0BMjANBgkqhkiG9w0BAQUFADCBiTELMAkGA1UEBhMC
    Tk8xEjAQBgNVBAgTCVRyb25kaGVpbTEQMA4GA1UEChMHVU5JTkVUVDEOMAwGA1UE
    CxMFRmVpZGUxGTAXBgNVBAMTEG9wZW5pZHAuZmVpZGUubm8xKTAnBgkqhkiG9w0B
    CQEWGmFuZHJlYXMuc29sYmVyZ0B1bmluZXR0Lm5vMB4XDTA4MDUwODA5MjI0OFoX
    DTM1MDkyMzA5MjI0OFowgYkxCzAJBgNVBAYTAk5PMRIwEAYDVQQIEwlUcm9uZGhl
    aW0xEDAOBgNVBAoTB1VOSU5FVFQxDjAMBgNVBAsTBUZlaWRlMRkwFwYDVQQDExBv
    cGVuaWRwLmZlaWRlLm5vMSkwJwYJKoZIhvcNAQkBFhphbmRyZWFzLnNvbGJlcmdA
    dW5pbmV0dC5ubzCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAt8jLoqI1VTlx
    AZ2axiDIThWcAOXdu8KkVUWaN/SooO9O0QQ7KRUjSGKN9JK65AFRDXQkWPAu4Hln
    O4noYlFSLnYyDxI66LCr71x4lgFJjqLeAvB/GqBqFfIZ3YK/NrhnUqFwZu63nLrZ
    jcUZxNaPjOOSRSDaXpv1kb5k3jOiSGECAwEAATANBgkqhkiG9w0BAQUFAAOBgQBQ
    Yj4cAafWaYfjBU2zi1ElwStIaJ5nyp/s/8B8SAPK2T79McMyccP3wSW13LHkmM1j
    wKe3ACFXBvqGQN0IbcH49hu0FKhYFM/GPDJcIHFBsiyMBXChpye9vBaTNEBCtU3K
    jjyG0hRT2mAQ9h+bkPmOvlEo/aH0xR68Z9hw4PF13w==
    -----END CERTIFICATE-----
  saml_idp_sso_target_url: 'https://openidp.feide.no/simplesaml/saml2/idp/SSOService.php'
  saml_issuer: 'mybookingsapp'
  saml_name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
  saml_provider_name: 'saml'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  saml_idp_cert: <%= ENV["SAML_IDP_CERT"] %>
  saml_idp_sso_target_url: <%= ENV["SAML_IDP_SSO_TARGET_URL"] %>
  saml_issuer: <%= ENV["SAML_ISSUER"] %>
  saml_name_identifier_format: <%= ENV["SAML_NAME_IDENTIFIER_FORMAT"] %>
  saml_provider_name: <%= ENV["SAML_PROVIDER_NAME"] %>
