# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d322f0d42628f98c33efce59860ed5f6dad593d9593a93a0398e00fa8da8e7b6ac19aca3febcec94a41da64d33582925cf0726fed0e9fe2127dc77a97c1b589e
  saml_provider_name: 'saml'
  saml_issuer: 'dummy'
  saml_idp_metadata_target_url: 'http://idp.deliriumcoder.es/simplesaml/saml2/idp/metadata.php'
  saml_private_key: ''
  saml_certificate: ''

test:
  secret_key_base: 250c2f28f99ca1df014b103e7ce999c4c47aefe26a60ca5881bf41ae5c91ecc7e6ff8714c448cab42b4ae13a77fb31bd1395e5c80118fa3c5c40f0c06ae89059
  saml_provider_name: 'saml'
  saml_issuer: 'dummy'
  saml_idp_metadata_target_url: 'http://idp.deliriumcoder.es/simplesaml/saml2/idp/metadata.php'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  saml_provider_name: <%= ENV["SAML_PROVIDER_NAME"] %>
  saml_issuer: <%= ENV["SAML_ISSUER"] %>
  saml_idp_metadata_target_url: <%= ENV["SAML_IDP_METADATA_TARGET_URL"] %>
