default: &default
  # secret_key_base:
  # saml_idp_cert:
  # saml_idp_sso_target_url:
  # saml_issuer:
  # saml_name_identifier_format:
  # saml_provider_name:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
